### PR TITLE
update path relative to root folder

### PR DESCRIPTION
**Pull request by edd34**
In order to ease the integration of the project, it's preferable to use "~" for path relative to root.

### CODE REVIEW

**Review by njt1982 — CHANGES_REQUESTED** [review]
Locally, this does not build the site for me... IIRC I did try this but had to use `../` to avoid this problem:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                                 09:39:34

 error  in ./src/App.vue?vue&type=style&index=0&lang=scss&

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: File to import not found or unreadable: ~/node_modules/bootstrap/scss/bootstrap.scss.
        on line 36 of /Users/nthompson/Sites/kids-word-search/src/App.vue
>> @import '~/node_modules/bootstrap/scss/bootstrap.scss';

   ^

    at /Users/nthompson/Sites/kids-word-search/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/nthompson/Sites/kids-word-search/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/nthompson/Sites/kids-word-search/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/nthompson/Sites/kids-word-search/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/Users/nthompson/Sites/kids-word-search/node_modules/sass-loader/dist/index.js:73:7)
    at Object.done [as callback] (/Users/nthompson/Sites/kids-word-search/node_modules/neo-async/async.js:8069:18)
    at options.error (/Users/nthompson/Sites/kids-word-search/node_modules/node-sass/lib/index.js:294:32)

 @ ./src/App.vue?vue&type=style&index=0&lang=scss& 1:0-480 1:0-480
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by njt1982** [comment]
Apparently this is a problem with `node-sass`... https://stackoverflow.com/a/57872804/224707

Will probably go away in the future if I ever get around to upgrading this project.

**Comment by edd34** [comment]
Hi @njt1982 , the solution was to use this syntax ```@import '~bootstrap/scss/bootstrap.scss';``` as stated in the link you provided.
It should compile !
Now your project can be plugged into another easily without worrying too much about relative path to node_modules (number of "../")

See https://github.com/webpack-contrib/sass-loader#resolving-import-at-rules

**Review by njt1982 — APPROVED** [review]
Yup - works!

**Pull request merged**
